### ISSUE TITLE
(phi0474.001) CTS and EpiDoc conversion

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-latinLit#101]

**Comment by lcerrato** [comment]
changes made to files

front matter was outside of div type="X" so I moved this into a chapter n=0
specified that the head was type commentary, resp of editor

put logs in chronological order; removed commented out logs; removed time and revision x.x info

**Comment by lcerrato** [comment]
I thought these were cts compliant but they are not.
If I have sections that span chapters, I take it I should make the section the div and make the chapters milestones? @balmas @TDBuck thoughts?

**Comment by PonteIneptique** [comment]
Hey Lisa, just weighing in :)
From what I saw, chapter and section should be div (at least in the Latin this is the case). As for the front matter, this can be added in body/div[@type="commentary"] :)

**Comment by balmas** [comment]
Ah but these are ones where we have multiple citation hierarchies that conflict right? It's either sections or chapters, but not chapter.section?

**Comment by lcerrato** [comment]
Thanks, both.

Yes there is a conflict. A chapter does not necessarily contain the entirety of a section and a section can span two chapters.

I find it helpful to look at the standard legacy citations as outlined in canonical sources. In this case, OLD tells me that this is referred to by work:section -- the chapters are not a standard part of the work. I think that is going to be more helpful in some cases than the wiki page.

Unfortunately, I don't know if an easy way to communicate this to collaborators as it's not an obvious thing.

I didn't plan on doing this work, but it was the first in the outstanding PR. I am rethinking that approach.

**Comment by PonteIneptique** [comment]
@lcerrato I might go with some of the text in Quintilian or Cicero during the training in two weeks. Want to save me some :') ?

**Comment by lcerrato** [comment]
I didn't plan on doing Latin. This is a review of the work done here
https://github.com/PerseusDL/canonical-latinLit/pull/100
so I am trying to address the gaps in the workflow and provide useful feedback for this work.
