### ISSUE TITLE
(phi0474.phi002) CTS and EpiDoc conversion

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-latinLit#106]
incorporating changes from https://github.com/PerseusDL/canonical-latinLit/pull/100

**Comment by lcerrato** [comment]
@balmas As lat2 now uses a different canonical cit scheme from eng2, do you object to my changing lat2 to correspond with phi0474.phi002-eng2 (and phi0474.phi001) which both use sections?

**Comment by balmas** [comment]
No objections.  I will enter an issue in the perseids_docs tracker for myself to double check for any annotations which reference this text and update them if necessary.

**Comment by lcerrato** [comment]
I have a couple of outstanding PRs so I'd like to know that these are ok before plowing ahead too far with incorrect stuff.
