### ISSUE TITLE
(phi0134.phi002.perseus-lat) file conversion

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-latinLit#135]
created new branch to integrate changes from https://github.com/PerseusDL/canonical-latinLit/pull/133

**Comment by lcerrato** [comment]
added missing three letter language codes

corrected change logs to 1) better format for comparison 2) capture missing information

**Comment by lcerrato** [comment]
The Latin looks good in terms of structure, but the English does not.
The lines in the English are not containers: they are only milestones.

**Comment by lcerrato** [comment]
Also, lines are badly placed in regard to notes (they end lines before the note, rather than ending at the end of the note).

Will require more work on the English files.

**Comment by zachhimes** [comment]
I can fix the line placement issue.

**Comment by lcerrato** [comment]
@zachhimes I would prefer that we go back to prose as these text require both line matchup and numerous structural revisions that are not fully documented.

**Comment by lcerrato** [comment]
closed via #136
