### ISSUE TITLE
(phi0474.phi007.perseus-lat/eng-1) EpiDoc and CTS conversions

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-latinLit#141]
using examples of phi0474.phi001 -- 006

- [ ] convert revision description to change log (follow format of when before who); dated order

- [ ] convert refsDecl; comment out old refsDecl

- [ ] make section default hierarchy

- [ ] check paragraphs against source book to be sure of placement

- [ ] general cleanup of formatting and tags

**Comment by lcerrato** [comment]
For reference: 

Latin http://babel.hathitrust.org/cgi/pt?id=njp.32101073249417;view=1up;seq=7
English https://archive.org/stream/orationsofmarcus02ciceuoft#page/16/mode/2up

**Comment by lcerrato** [comment]
@zachhimes If you want to continue with this series, feel free. (phi0474.phi006 looks good!)

**Comment by zachhimes** [comment]
@lcerrato, ok I'll try to do that.

**Comment by zachhimes** [comment]
@lcerrato I have a question regarding how sections should be tagged in phi0474.phi007.perseus-lat1. Sections are sometimes not contained in a single chapter (for example, section 19 begins in chapter 8 and ends in chapter 9). Should sections be tagged as milestones (I assume chapters should be tagged as divs)?

**Comment by lcerrato** [comment]
No, the sections should be the divs and the chapters should be milestones, as with the other works in phi0474 so far.

Sections are the canonical default and since they span chapters we can't nest them inside each other. This was a problem with most of the other orations (if not all).

Thanks for checking.
