### ISSUE TITLE
phi0845 conversion

### ISSUE THREAD

**Issue by PonteIneptique** [PerseusDL/canonical-latinLit#193]
- [x] Merge volumes as they are composite (Notice to @lcerrato regarding this, might need to change something in the catalog)
- [x] Epidoc
- [x] CapiTainS
- [x] Metadata
- [x] Bump URN

**Comment by PonteIneptique** [comment]
And once again, I forget the PR...

**Comment by PonteIneptique** [comment]
As a result of forgetting the PR, I added master as a protected branch.

**Comment by lcerrato** [comment]
Hi @PonteIneptique 
Please submit catalog data corrections (if needed) via an issue to catalog_data.
https://github.com/PerseusDL/catalog_data/issues

**Comment by PonteIneptique** [comment]
Fixed by @47bf740
