### ISSUE TITLE
Ovid, Metamorphoses (phi0959.phi006.perseus-lat2.xml), 3: line numbering different from the original

### ISSUE THREAD

**Issue by nevenjovanovic** [PerseusDL/canonical-latinLit#211]
The XML phi0959.phi006.perseus-lat2.xml is supposed to be a digital edition of Die Metamorphosen / des P. Ovidius Naso. Nach Text und Kommentar getrennte ausg. für den Schulgebrauch von Hugo Magnus, Gotha : Friedr. Andr. Perthes, 1886-1903 (v. 1, 1892). (Cf. facsimiles [Hathi Trust](https://catalog.hathitrust.org/Record/100674420), [archive.org](https://archive.org/details/bub_gb_ycgzAQAAMAAJ)) However, after the line 3.250 (p. 92 of the archive.org facsimile), the line numbering in the XML edition starts to differ. The editor, Magnus, has actually suppressed two lines 250-251 as inauthentic, but has continued to count them for line numbering. This is not registered in the XML edition.
I propose to include the two inauthentic lines (marking them as ``<del>``) and change the numbering in Met. 3 accordingly. The similar intervention seems to have already been carried out in 8.285-286.
If this is OK with the editors, I could make the necessary changes and submit the pull request.

**Comment by lcerrato** [comment]
Hi @nevenjovanovic 
I see these lines in a handful of print editions — presented in line without comment.
According to the header, the text was corrected against both 1892 and 1914 eds.
1892 deletes the lines but notes this in the footer; 1914 includes the lines in the running text. It's possible the Perseus editors decided not to include the lines for another reason but I suspect there was just some source confusion here.

The first option is to correct per your suggestion: add lines and tag as `<del>`. This is supported by the earlier print edition. https://babel.hathitrust.org/cgi/pt?id=uc1.b4036515;view=2up;seq=116 is better.

Second option is to add inline without any further notation, supported by https://archive.org/stream/metamorphoseonli00oviduoft#page/102/mode/2up

Third option is to do nothing and/or add a note, based on the fact that the prior Perseus editors did this intentionally and that the CTS numbering need not have any direct relationship to print.

I agree with you and think that the first option is best as it pertains to the 2 lines, as we are asserting the earlier edition is source of this work (although I have my doubts). 

We'd be happy for you to submit a pull request on this. Note, I'm equally fine with making the corrections here.

**Comment by nevenjovanovic** [comment]
@lcerrato -- I have examined the 1914 Magnus edition, and the [first volume of 1892](http://www.archive.org/details/bub_gb_BetEAQAAIAAJ) edition (further volumes are not on archive.org and I cannot access them from Europe without using a US-proxy). The 1914 edition differs considerably from the 1892; the 1914 is much more restrained in deleting lines:

Marked as deleted, missing in XML: 1, 546-547 (two half-lines, which become 547a in 1914, where the order of lines is changed as well); 3, 251-252 (not deleted in the 1914 edition).

Magnus's deletions from 1892: 4, 436-438 (not deleted in 1914); 4, 803-804 (1914 has 803 lines, no deletions); 8, 87 (not deleted in 1914); 9, 729 (not deleted in 1914); 11, 71-72 (not deleted in 1914); 11, 293 (quantum pro iam tum! 1914 not deleted; reads iam tum); 11, 714 (variants: quae dum tota locis / dumque notata oculis; not deleted in 1914; reads dumque notata locis)

A comparison of number of lines for individual books (1892 and XML, differences marked with !):
1 = 779 (! XML 778)
2 = 875 (XML 875)
3 = 733 (! XML 731)
4 = 801 / 803 (! XML 804)
5 = 678 (XML 678)
6 = 721 (XML 721)
7 = 865 (XML 865)
8 = 884 (! XML 887)
9 = 797 (XML 797)
10 = 739 (XML 739)
11 = 795 (XML 795)
12 = 628 (XML 628)
13 = 968 (XML 968)
14 = 851 (XML 851)
15 = 879 (XML 879)
The 1892 and 1914 edition differ to such a degree that the one cannot be "corrected against" the other without creating a hybrid and introducing new interpretations. I would propose to follow the 1914 edition and update the TEI header to express that.

**Comment by lcerrato** [comment]
As the choice of edition affects not only the header but also the cataloging data for the work, I would want to reexamine where we are with this.

Some texts — especially the Perseus Latin — do not follow a clear provenance. It may be the case that the editor did in fact pick and choose between 1892 and 1914 based on some other electronic text. This is not uncommon with many Perseus Latin texts. Often the various print editions were not in fact on hand for cross reference or the information on the source text was simply wrong or incomplete. 

In cases like this where there is potentially a good deal of work required in trying to achieve the correct edition, we have generally decided to replace the edition with something rescanned and reentered via the Open Philology work.

As I have invested a lot of time working on just this issue for other works, trying to regularize against the 1892 edition is in keeping with what I have done previously.
