### ISSUE TITLE
Amphitruo  (phi0119.phi001) has overwritten Pseudolus (phi0119.phi016)

### ISSUE THREAD

**Issue by knoxdw** [PerseusDL/canonical-latinLit#231]
phi0119.phi016.perseus-lat2.xml is apparently supposed to be Plautus's Pseudolus, but it appears instead to be a copy of a version of Amphitruo.

**Comment by lcerrato** [comment]
@knoxdw There should be a corrected file here now. I noticed some inconsistencies in the markup in this group so that will have to be addressed at another time.
Thanks!
