### ISSUE TITLE
Plautus Miles Gloriosus has inconsistent refsDecl

### ISSUE THREAD

**Issue by jtauber** [PerseusDL/canonical-latinLit#236]
Part of the problem reported in https://github.com/scaife-viewer/scaife-viewer/issues/189 (see the last few comments) was this:

https://github.com/PerseusDL/canonical-latinLit/blob/master/data/phi0119/phi012/phi0119.phi012.perseus-eng2.xml#L39

which confuses cards and lines.

**Comment by lcerrato** [comment]
I expect this will be evident in the entire Plautus translation corpus if these were globally converted. 
I spot other issues in this text, as well.

**Comment by lcerrato** [comment]
fixed #238
