### ISSUE TITLE
incorrect title? stoa0058.stoa003.perseus-lat1

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-latinLit#237]
Boethius, Quomodo Substantiae in Eo Quod Sint Bonae Sint Cum Non Sint Substanialia Bona 
H.F. Stewart, Ed.

user reports "Substantialia instead of substanialia"

see https://babel.hathitrust.org/cgi/pt?id=njp.32101077773974;view=1up;seq=58

**Comment by AlisonBabeu** [comment]
Hey @lcerrato  thanks for catching this. I've correct this typo in the cite collections work title list and will fix the source files in catalog_data.
