### ISSUE TITLE
(phi1254.phi001.perseus-lat2) various conversion problems and errors

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-latinLit#304]
book 1 - chapter 2 - section 2: note not inline (move to previous p)
book 1 - chapter 3 - section 26: bad Greek character(s):        :   \x3A
book 1 - chapter 6 - section 5: " in data (use q or quote, ldquo, rdquo)
book 1 - chapter 7 - section 2: " in data
book 1 - chapter 11 - section 8 - line : bad Greek character(s):      )   \x29
book 1 - chapter 15 - section 7: `<p>` immediately followed by <note>! (move at the end of previous `<p>`)
book 1 - chapter 16 - section 12: `<p>` immediately followed by `<note>`!
book 2 - chapter 18 - section 9: Ξενιθ́δης instead of Ξενιάδης
book 2 - chapter 18 - section 9: bad Greek character(s):          ́   \x301
book 2 - chapter 23 - section 9 - line : bad Greek character(s):         :   \x3A
book 2 - chapter 23 - section 10 - line : " in data
book 2 - chapter 23 - section 10 - line : double i in Íimpetrarit
book 2 - chapter 23 - section 10 - line : " in data
book 2 - chapter 23 - section 12 - line : bad Greek character(s):      )   \x29
book 3 - chapter 8 - section 7 - line : " in data
book 3 - chapter 8 - section 7: " in data
book 4 - chapter 8 - section 8: `<p>` immediately followed by `<note>`!
book 5 - chapter 13 - section 2: `<p>` immediately followed by `<note>`!
book 7 - chapter 6: markup error: head twice instead of div argument
book 9 - chapter 3 - section 6: bad Greek character(s):     :   \x3A
book 11 - chapter 2 - section 3: `<p>` immediately followed by `<note>`!
book 12 - chapter 5 - section 10: " in data
book 12 - chapter 5 - section 11: " in data
book 13 - chapter 8 - section 3: `<p>` immediately followed by `<note>`!
book 13 - chapter 31 - section 14: bad Greek character(s):     ̣   \x323
book 17 - chapter 12 - section 5: bad Greek character(s): !   \x21
book 18 - chapter 9 - section 5 - line : bad Greek character(s):      ̓   \x313
book 18 - chapter 10 - section 11: bad Greek character(s):      ́   \x301
book 18 - chapter 12 - section 2 - line : bad Greek character(s): d O P X   \x64  \x4F  \x50  \x58
book 19 - chapter 11 - section 2 - line : bad Greek character(s): )   \x29
book 20 - chapter 1 - section 13: bad Greek character(s): d   \x64
book 20 - chapter 1 - section 13: bad Greek character(s): P   \x50
book 20 - chapter 1 - section 13: bad Greek character(s): P X   \x50  \x58
book 20 - chapter 1 - section 16: bad Greek character(s): P Z   \x50  \x5A
book 20 - chapter 5 - section 11: bad Greek character(s): P l u t   \x50  \x6C  \x75  \x74

**Comment by lcerrato** [comment]
separating the issue into two PRs to avoid potential for conflicts

**Comment by aurelberra** [comment]
Thank you!

**Comment by lcerrato** [comment]
fixed via #329
