### ISSUE TITLE
(phi0474.phi001.perseus-lat2) various conversion errors and problems

### ISSUE THREAD

**Issue by klausdeiser** [PerseusDL/canonical-latinLit#309]
edition urn:cts:latinLit:phi0474.phi001.perseus-lat2 - section 55: " in data, use q or quote instead
edition urn:cts:latinLit:phi0474.phi001.perseus-lat2 - section 84: videtur not videtvr

**Comment by lcerrato** [comment]
@klausdeiser 
Thank you!
