### ISSUE TITLE
(phi1221.phi007) missing file

### ISSUE THREAD

**Issue by HelenaSabel** [PerseusDL/canonical-latinLit#311]
The Latin version of the work _Res Gestae Divi Augusti_ is referenced as `canonical-latinLit/data/phi1221/phi007/phi1221.phi007.perseus-lat1.xml` but there is no file with that path.

**Comment by lcerrato** [comment]
Hi @HelenaSabel 
According to the son file in the directory, there is a copyright flag on this work. This means that we cannot confirm that it is clearly in the public domain so we did not move it to GitHub.
It either needs to be replaced or we need to determine that we can reuse the version in Perseus.

**Comment by HelenaSabel** [comment]
Thank you so much @lcerrato  for your prompt answer. I didn‘t notice the flag.
We are compiling a corpus to study modality in Latin and Perseus is a great resource. This is not the forum to post this question, but maybe you are willing to give some insight into this issue: how could I know that the works that are only available on Perseus website can be reused?

**Comment by lcerrato** [comment]
Hi @HelenaSabel 
Only works that have been released under a Creative Commons license are available, as noted in the Help: http://www.perseus.tufts.edu/hopper/help/copyright#down

The help pages describe what to look for when reading a text.

These are works available in previous download packages (http://www.perseus.tufts.edu/hopper/opensource/download) via Perseus 4, which have been moved over to GitHub. There may be one or two changes where we subsequently discovered works should or should not have been released, but these are minor.

We are happy to answer questions about particular works either here or via the webmaster:
https://github.com/PerseusDL/canonical-latinLit/wiki/Contact-us!

**Comment by HelenaSabel** [comment]
Thank you for the answer @lcerrato (and apologies for leaving the issue open for so long!)
