### ISSUE TITLE
(phi0448.phi001.perseus-lat2.xml:2.4.4) typo

### ISSUE THREAD

**Issue by gcelano** [PerseusDL/canonical-latinLit#315]
2.4.4: "propinquitatibus adfinitatibus quo" should probably be changed into "propinquitatibus adfinitatibusque"

**Comment by lcerrato** [comment]
per https://babel.hathitrust.org/cgi/pt?id=mdp.39015004885375&view=2up&seq=142

**Comment by lcerrato** [comment]
Thanks @gcelano
