### ISSUE TITLE
(phi0631.phi002.perseus-lat3) remaining hyphens

### ISSUE THREAD

**Issue by nevenjovanovic** [PerseusDL/canonical-latinLit#319]
There are about 34 remaining unannotated hyphens (hyphen + whitespace) in Sallust's Jugurtha, https://raw.githubusercontent.com/PerseusDL/canonical-latinLit/master/data/phi0631/phi002/phi0631.phi002.perseus-lat3.xml -- for example: `fa- teor, hon ha- beo, no- bilitas, ne- que, dice- rem, op- tumus, au- daciam, mul- titudine`. I could correct the text and make a pull request, if necessary.

**Comment by lcerrato** [comment]
@nevenjovanovic 
We would be happy to have those corrections. Otherwise, we can just leave this open and it will be corrected in the next batch of work.
