### ISSUE TITLE
(global) Set of OCR errors — invalid Latin words

### ISSUE THREAD

**Issue by PonteIneptique** [PerseusDL/canonical-latinLit#335]
Hi there !
On twitter, I saw Logeion sharing this feedback from a reader : https://twitter.com/LogeionGkLat/status/1187039402142371840

There is few turn->tum, at least one earn->eam errors. The tweet seems to refer to more kind of errors though.

**Comment by PonteIneptique** [comment]
The same error can be found in (excluding notes.) : 

- phi1017.011 ( once )
- phi0474.046 (multiple times, earn as well)
- phi0474.038 (multiple times, earn as well)
- phi0474.039 (multiple times, earn as well)
- phi0474.40 ( earn only ?)
- phi0474.045
- phi0474.046  (? times, earn as well)
- phi0474.048  (? times, earn as well)
- phi0474.049
- phi0474.050 (earn only ?)
- phi0474.055   (? times, earn as well)
- phi0914.phi001 (earn only ?)
- phi0914.phi012 (earn only ?)
- phi0978.phi001 (multiple times, earn as well)
- phi1002.001 (earn only)
- phi1035.001.lat2 (multiple times)
- phi1254.001.lat2 (multiple times)
- stoa0023.001 (earn only)

 https://github.com/PerseusDL/canonical-latinLit/blob/c1c36f48ed4a6bd0bc87618103e18391e0d1d512/data/phi1035/phi001/phi1035.phi001.perseus-lat2.xml#L4995

https://github.com/PerseusDL/canonical-latinLit/blob/c1c36f48ed4a6bd0bc87618103e18391e0d1d512/data/phi1017/phi011/phi1017.phi011.perseus-lat2.xml#L230

https://github.com/PerseusDL/canonical-latinLit/blob/c1c36f48ed4a6bd0bc87618103e18391e0d1d512/data/phi0474/phi046/phi0474.phi046.perseus-lat1.xml#L87

I am probably gonna propose a PR, using search and replace with a filter...

**Comment by helmadik** [comment]
I tested for the string rn in unparsed words. The original issues reported included dignitatern, turn, also priris for primis, unfortunately.. Since the cluster rn doesn't show up at word beginning or word end, that also gives you a way to find a lot of them.

**Comment by lcerrato** [comment]
@helmadik @PonteIneptique 
Yes there are extensive OCR issues in Latin and Greek texts. There are lots of issues with that early Latin OCR batch (as well as the Greek). It was an in house experiment with commercial OCR. There was supposed to be a run through morpheus for invalid forms when these texts were entered — I see plenty of evidence that didn't always happen.

When we complete CTS conversion (I am not doing so in Latin presently) there is more of a read through wherein we (I) spot these types things and then I usually globally search on them.

In the meantime, there are issues I am working on on the Greek side and there have been lots of corrections to texts in the Scaife Viewer for which I have regular penpals.

Adding to this issue with a list of things to look for would be appreciated. A pull request is not ideal in the present workflow.

**Comment by lcerrato** [comment]
I should also add that I keep typos issues open in both repos in order to track this sort of thing.
And thanks for the heads up.

**Comment by PonteIneptique** [comment]
In the context of my PhD, it would make sense that I fix these, and would be happy to. I would also be happy to separate the concerns (turn in 1 PR, earn in another) and checking them manually. Would you disagree with that ? 
It's just that a clean corpus is definitely important and as I use github release for citability, this is important to me. I'd like to avoid forking and citing my version if I can. 
Anyway, thanks to you both :)

**Comment by helmadik** [comment]
-rnus for 1pl -mus also showed up a number of times. I attach a screenshot of some of my edit actions in case they are helpful. 
![image](https://user-images.githubusercontent.com/7517297/67496117-8ec39400-f641-11e9-8144-4d26ea689a18.png)

**Comment by helmadik** [comment]
@PonteIneptique another place to start could be the handful of files where correction was done and the original OCR error was preserved in the xml. Searching for <corr I get the following (including one English translation where several 'arguments' have been replaced with 'argumentis' :-))
![image](https://user-images.githubusercontent.com/7517297/67507449-86c11f80-f654-11e9-85a3-85d3b3bb4457.png)

**Comment by PonteIneptique** [comment]
I think I'll stop myself at turn, earn and \Wrn as they are evident.
For the other, we'll see another time but I do not them :)

**Comment by lcerrato** [comment]
Hi @PonteIneptique 

I understand your concern. But longstanding (10 or 20 years old) typographical errors are less of a priority than the serious conversion errors, irregularities, and omissions that I am sorting through on a daily basis. 

I would really not prefer any large PRs right now. Single text PRs are preferable based on what I am trying to accomplish with the regularization of the collection.

I am happy to make global corrections to any patterns you have noticed as above (turn and earn) and feel free to add others here.

Once I am caught up with the backlog of stuff I will take a look at this and update here.
 
I should add in the long term, it has always been the plan to add more editions and use the new data to crosscheck the existing data but conversion needs to be accomplished in order to get more of this data out there for reuse. The priority is more editions and more (sometimes raw) data.

**Comment by PonteIneptique** [comment]
Thanks a lot @lcerrato :) 
By the way, in some of the diff, I noticed some more issues with hyphenization ( https://github.com/PerseusDL/canonical-latinLit/blob/6b71b93870f9a9d05f1ce9a50a5f90a15d55e737/data/phi0474/phi042/phi0474.phi042.perseus-lat1.xml#L141 ) which seems easy to fix as they kept new lines in there :)

**Comment by lcerrato** [comment]
fixed via #339
