### ISSUE TITLE
typo in phi0448.phi002 Caesar de bello civili liber II

### ISSUE THREAD

**Issue by PhVerkerk** [PerseusDL/canonical-latinLit#342]
On line 817 (book 2, chapter 32, section 8) a surprizing "benefficio". 
An hyphen (and line-break) in the original PHI/lat0448.txt has been converted into a double f.
"non proditi per illum Caesaris benefficio estis conservati?"
versus
"non proditi per illum Caesaris bene-
ficio estis conservati?"
Yours.

**Comment by lcerrato** [comment]
@PhVerkerk 
Thank you for the report!
