### ISSUE TITLE
Phi0959.phi002.perseus-eng1 has inconsistent unit attribute

### ISSUE THREAD

**Issue by PonteIneptique** [PerseusDL/canonical-latinLit#36]
Hi there,
To me, it seems that all units in https://github.com/PerseusDL/canonical-latinLit/blob/master/data/phi0959/phi002/phi0959.phi002.perseus-eng1.xml refer to the same thing (*ie.* line) but we can encounter "line", "sync" and "card" in the same file. Could you confirm before I unite them ?

**Comment by lcerrato** [comment]
In looking here
https://books.google.com/books?id=1gLgAAAAMAAJ&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false
there are poems.
So for the translation, all of the milestones would have been added by hand and I'm guessing that sync and carte are there for alignment purposes.

**Comment by AlisonBabeu** [comment]
I have to admit I have nothing useful to add to this conversation other than I think that Lisa is right!

**Comment by PonteIneptique** [comment]
Thanks both, I'll assign @lcerrato to this kind of issues from now on.
Looking at further English translation, milestone unit, while clearly referring to the same thing, did not use the same term. I'll merge all of that when required (ie line, card, carte and sync)

**Comment by PonteIneptique** [comment]
So, I looked at it again this morning, to see how I could rearrange stuff. Problem is, paragraph have milestone in p sometimes, in an irregular fashion (mainly first poems). According to the printed book, the paragraph markup we added does not exist.

According to http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0085%3Apoem%3D1%3Acarte%3D53, the first paragraph does not even exist (Might be a serious bug here !) which clearly starts with "Dear Ulysse" as in the xml.

The display in Perseus will probably lead me to copy this citation scheme for the moment (aka cards) and ignore milestone inside paragraphs :)

**Comment by balmas** [comment]
@PonteIneptique so what about the first paragraph? is that now registered as as separate bug to be addressed later?

**Comment by PonteIneptique** [comment]
There is two different issues : 
- [ ] Adding the card n1, which I did for each poem
- [ ] Updating Perseus website :)

**Comment by balmas** [comment]
Oh misunderstood - I will merge

**Comment by lcerrato** [comment]
Yes, this is common Perseus bug due to the competing text structure tags. I saw it when I looked at the text.
You can see the text if you view a bigger chunk (such as the whole poem). 
Right now, we handle P4 based text errors on a separate system, but it may not be worth the effort to try to fix this in P4 since the workaround is available.
In any case I will send to webmaster for future reference.
