### ISSUE TITLE
Schema reference in files

### ISSUE THREAD

**Issue by gcelano** [PerseusDL/canonical-latinLit#364]
In many files, I find the reference to the schema href="http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng", where the content of "latest" is however supposed to change over time. Is this an error?

**Comment by lcerrato** [comment]
@gcelano 
Hi!!
No, this is preferred to locking in a specific version of the schema and follows the convention at Open Greek and Latin and the recommendation for active projects: http://epidoc.stoa.org/schema/latest/.

**Comment by gcelano** [comment]
Hi @lcerrato!

What I am wondering is: is the "latest" schema guaranteed to be always backward-compatible?

**Comment by lcerrato** [comment]
No, but as we are regularly updating all of the repos, we can easily spot any issues that arise. (We'd go from 100% passing in OGL to an error, for instance.)
If we were not in development and no one was working on these, we'd want to lock in a version.

I saw only one recent instance where this was a problem in the last three or four years.

**Comment by lcerrato** [comment]
Following best practice as recommended by working group.
