### ISSUE TITLE
slashes in phi0474.phi056.perseus-lat1.xml

### ISSUE THREAD

**Issue by gcelano** [PerseusDL/canonical-latinLit#367]
there are lines encoded so:

`<l>Ubi no/minabit Phae/driam, tu <reg>pa</reg>/mphilam</l>`

with slashes, which disturb tokenization: what is the meaning of them? Can we get rid of them/change? None is 
present here (p. 74): 

https://ryanfb.github.io/loebolus-data/L205N.pdf

**Comment by lcerrato** [comment]
This is not a Loeb, so you have to look here:
https://archive.org/details/epistulaerecogno01ciceuoft/page/24/mode/2up?q=Phaedriam

It looks like they are supposed to represent stress?

As this is not a converted text, it is not something we would have noticed until the conversion was done.

**Comment by gcelano** [comment]
I see, well, I would still use the correct Unicode characters, such as ó
