### ISSUE TITLE
Citation scheme of urn:cts:latinLit:phi0959.phi003.perseus-lat2

### ISSUE THREAD

**Issue by PonteIneptique** [PerseusDL/canonical-latinLit#37]
Right now, the Data preservation URI is  http://data.perseus.org/citations/urn:cts:latinLit:phi0959.phi003.perseus-lat1:Med.

Which is not CTS compliant. When moved to epidoc, I conserved the main div for the poem. Through, we only have one poem (1 object at level 1) and lines under it. Could we just move it to lines only before it gets used...

PS : @lcerrato @balmas @AlisonBabeu I don't know who to assign those "philological questions". Feel free to tell me :)

**Comment by lcerrato** [comment]
This looks like an artifact of the splitting of a grouped text.


If we reinstitute the Perseus grouping/sorting by format (e.g. "show all Latin Poetry in Perseus"), a lost feature, we are going to get this information via catalog records, not texts themselves. This is already a catalog sorting feature.

Unless I'm missing something on the EpiDoc side, I don't see why it's needed.

**Comment by PonteIneptique** [comment]
I agree with you about the catalog thing you just said, and also the potential \@subtype (not \@type because it should contain textpart in Epidoc) or something close to it. But as you said, global preferences

**Comment by lcerrato** [comment]
Thanks! I claim no expertise in EpiDoc.
