### ISSUE TITLE
hane / hanc

### ISSUE THREAD

**Issue by gcelano** [PerseusDL/canonical-latinLit#374]
I found 12 examples of "hane" in

phi1002.phi001.perseus-lat2.xml
phi1254.phi001.perseus-lat2.xml
phi0845.phi002.perseus-lat3.xml
phi0914.phi001.perseus-lat2.xml
stoa0023.stoa001.perseus-lat1.xml
phi0972.phi001.perseus-lat2.xml
phi0978.phi001.perseus-lat2.xml
phi1020.phi001.perseus-lat2.xml
phi0836.phi002.perseus-lat5.xml
phi0474.phi055.perseus-lat1.xml
phi1017.phi011.perseus-lat2.xml
phi1017.phi013.perseus-lat2.xml

I think they should be "hanc": what do you think?

**Comment by lcerrato** [comment]
In general, I usually spot check things in context via Google Books, since most of this is there. 
I see 32 results in the collection via a Latin search on Perseus and get 73 hits in the whole collection (although some of those look like regularization corrections).
