### ISSUE TITLE
(phi1294.phi002.perseus-lat2.xml) header/metadata review

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-latinLit#408]
This was an early conversion and could use a header/metadata review.

**Comment by AlisonBabeu** [comment]
Hi @lcerrato so I did a first pass at this one. My greatest uncertainty was if I should add a role for the second editor and I almost went with role="reviser" as an attribute but we have no history of that at Perseus so I wasn't sure overall.

**Comment by AlisonBabeu** [comment]
I'm closing this issue as it has been resolved.
