### ISSUE TITLE
Misattribution of translation - Vergil's Aeneid

### ISSUE THREAD

**Issue by wolfwords** [PerseusDL/canonical-latinLit#430]
Hi!

I'm new to GitHub so I'm not sure how to log this but I was looking for a translation of Vergil's Aeneid and it seems to have been misattributed. The Scaife viewer version seems to be the Theodore C Williams version from 1910, but it's been attributed to John Dryden (1697). Both versions exist in the Perseus Tufts database. I've attached screenshots of the first few lines from both for comparison. Thought I'd let you know!

Thanks. (:

<img width="755" alt="Screenshot 2021-06-03 at 11 45 08" src="https://user-images.githubusercontent.com/85282683/120616240-bf94bd80-c461-11eb-9964-384523503e6a.png">
<img width="610" alt="Screenshot 2021-06-03 at 11 46 16" src="https://user-images.githubusercontent.com/85282683/120616260-c28fae00-c461-11eb-8db3-8eec013cd772.png">
<img width="311" alt="Screenshot 2021-06-03 at 11 46 30" src="https://user-images.githubusercontent.com/85282683/120616269-c3c0db00-c461-11eb-9c8e-4992e6c670d1.png">
<img width="589" alt="Screenshot 2021-06-03 at 11 46 43" src="https://user-images.githubusercontent.com/85282683/120616283-c4f20800-c461-11eb-9454-8f4f38f21f57.png">

**Comment by AlisonBabeu** [comment]
Thank you for very much for documenting this incorrect attribution. I have corrected the metadata that was causing this display error and the edition information on the display page should appear correctly the next time the Scaife Viewer is updated. 

Best,

Alison Babeu
Digital Librarian, Perseus Digital Library
