### ISSUE TITLE
(phi0893.phi001.perseus-lat2.xml) delete a comma

### ISSUE THREAD

**Issue by sjhuskey** [PerseusDL/canonical-latinLit#496]
There is an extra comma in [Horace _Carmina_ 4.7.21](https://scaife.perseus.org/reader/urn:cts:latinLit:phi0893.phi001.perseus-lat2:4.7.21/). Instead of _cum semel occideris et de te, splendida, Minos_, the text should be _cum semel occideris et de te splendida Minos_ (without a comma before or after _splendida_. I checked this against two other editions.

**Comment by lcerrato** [comment]
@sjhuskey 
Thank you!
