### ISSUE TITLE
Typo in phi1348.abo011.perseus-eng2 on LINE 8

### ISSUE THREAD

**Issue by bolner** [PerseusDL/canonical-latinLit#547]
The `>` is duplicated:

https://github.com/PerseusDL/canonical-latinLit/blob/c5e7de0bba5ae12b0d3c5bf0b1008783b7b66d71/data/phi1348/abo011/phi1348.abo011.perseus-eng2.xml#L8

**Comment by lcerrato** [comment]
@bolner 
Thank you!
