### ISSUE TITLE
new phi0978.phi001

### ISSUE THREAD

**Issue by annettegessner** [PerseusDL/canonical-latinLit#99]
I have added the new Pliny text plus the two necessary __cts__ files on a new branch on my fork:
https://github.com/annettegessner/canonical-latinLit/tree/phi0978.phi001/data/phi0978/phi001
I am adding a list of things that have to be done, so I don't forget them during the holidays: 

ToDo:
- confirm or change new full URN: urn:cts:latinLit:phi0978.phi001.opp-lat8
- correct RefsDecl
- correct div-tags, convert milestones "section" to divs
- handle `<pb xml:id="v.1.p.1"/>` (pagenumbering - some appear more than once, hence document is not valid)
- ... ?

**Comment by annettegessner** [comment]
Replaced second occurrence of `<pb xml:id="v.4.p.1"/>` with `pb xml:id="v.4b.p.1"/>` and all following, so the document is valid now.
Added RefsDecl as in CSEL-files. 2 Levels: Book and Chapter. (Level "Section" is not needed for any chapter.) 
Numbering of textparts seems correct.

**Comment by PonteIneptique** [comment]
Where do you stand on this issue @annettegessner ?

**Comment by annettegessner** [comment]
Added `xml:lang="lat"` as element to div type="edition", just the way I learned it yesterday.
Passing hook test now. Just created pull request.

**Comment by annettegessner** [comment]
We're not sure about the URN yet, please check!
There is 
urn:cts:latinLit:phi0978.phi001.perseus-lat1
which is also Mayhoff 1906, just as this edition, but it might be a completely new scan.
(See mail conversation from 12..17.12.2015.)

**Comment by annettegessner** [comment]
Changed URN to perseus-lat2, reserved the URN, changed files appropriately, passing hook test.

**Comment by annettegessner** [comment]
improved the header
pull request merged
closing issue

**Comment by lcerrato** [comment]
@gregorycrane Was this the text you referred to this morning? There are some issues: see
https://github.com/PerseusDL/canonical-latinLit/issues/147
